const db=supabase.createClient('https://uklivylyenatdqbgmcxy.supabase.co','sb_publishable_ntlKWYQvMXlCs_obIEVIIA_-CfxOFTJ');const PRICE=10,TOTAL_PIXELS=22500,$=id=>document.getElementById(id),board=$('pixelBoard'),selected=new Set();let pixels=[],scale=1,currentUser=null;
const money=n=>n.toLocaleString('en-US')+' جنيه';
function normalizePhone(v){let x=String(v||'').replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[^0-9+]/g,'');if(x.startsWith('00'))x='+'+x.slice(2);if(x.startsWith('01'))x='+20'+x.slice(1);if(x.startsWith('20')&&!x.startsWith('+'))x='+'+x;return x}
function setAuthUI(){const logged=!!currentUser;$('accountStatus').textContent=logged?'حسابك مسجل الدخول':'زائر';$('loginButton').classList.toggle('hidden',logged);$('logoutButton').classList.toggle('hidden',!logged)}
function authMode(mode){$('loginForm').classList.toggle('hidden',mode!=='login');$('signupForm').classList.toggle('hidden',mode!=='signup');$('resetForm').classList.toggle('hidden',mode!=='reset');$('loginTab').classList.toggle('active',mode==='login');$('signupTab').classList.toggle('active',mode==='signup')}
$('loginButton').onclick=()=>{authMode('login');open('authModal')};$('loginTab').onclick=()=>authMode('login');$('signupTab').onclick=()=>authMode('signup');$('forgotPassword').onclick=()=>authMode('reset');$('backToLogin').onclick=()=>authMode('login');$('logoutButton').onclick=async()=>{await db.auth.signOut();selected.clear();totals()};
$('sendLoginOtp').onclick=async()=>{const phone=normalizePhone($('loginPhone').value);if(!phone)return $('loginMsg').textContent='اكتب رقم الموبايل الأول.';$('sendLoginOtp').disabled=true;$('loginMsg').textContent='جاري إرسال كود الدخول...';try{const{error}=await db.auth.signInWithOtp({phone,options:{shouldCreateUser:false}});if(error){$('loginMsg').textContent='تعذر إرسال كود الدخول: '+error.message}else{$('loginOtpBox').classList.remove('hidden');$('loginMsg').textContent='لو الرقم مسجل وإعداد SMS مضبوط، هيوصلك كود الدخول.'}}catch(e){$('loginMsg').textContent='حصل خطأ في الاتصال. جرّب تاني.'}finally{$('sendLoginOtp').disabled=false}};
$('verifyLoginOtp').onclick=async()=>{const phone=normalizePhone($('loginPhone').value),token=$('loginOtp').value.trim();if(!phone||!token)return $('loginMsg').textContent='اكتب رقم الموبايل وكود الدخول.';$('verifyLoginOtp').disabled=true;$('loginMsg').textContent='جاري التحقق...';try{const{error}=await db.auth.verifyOtp({phone,token,type:'sms'});if(error){$('loginMsg').textContent='الكود غير صحيح أو انتهت صلاحيته: '+error.message}else{$('loginMsg').textContent='تم تسجيل الدخول.';setTimeout(()=>close('authModal'),500)}}catch(e){$('loginMsg').textContent='حصل خطأ. جرّب تاني.'}finally{$('verifyLoginOtp').disabled=false}};
$('doLogin').onclick=async()=>{const phone=normalizePhone($('loginPhone').value),password=$('loginPassword').value;if(!phone||!password)return $('loginMsg').textContent='اكتب رقم الموبايل والباسورد.';$('doLogin').disabled=true;$('loginMsg').textContent='جاري الدخول...';try{const{error}=await db.auth.signInWithPassword({phone,password});if(error){const m=error.message||'';$('loginMsg').textContent=/phone.*(disabled|not enabled)|phone_provider_disabled/i.test(m)?'تسجيل الدخول بالموبايل غير مفعّل في Supabase.':/invalid login credentials|invalid_credentials/i.test(m)?'رقم الموبايل أو كلمة المرور غير صحيحة.':/phone_not_confirmed/i.test(m)?'لازم تأكيد رقم الموبايل قبل الدخول.':'تعذر تسجيل الدخول: '+m}else{$('loginMsg').textContent='تم تسجيل الدخول.';setTimeout(()=>close('authModal'),500)}}catch(e){$('loginMsg').textContent='حصل خطأ في الاتصال. جرّب تاني.'}finally{$('doLogin').disabled=false}};
$('doSignup').onclick=async()=>{const name=$('signupName').value.trim(),phone=normalizePhone($('signupPhone').value),password=$('signupPassword').value;if(!name||!phone||password.length<6)return $('signupMsg').textContent='اكتب الاسم والموبايل وباسورد 6 أحرف أو أكثر.';$('doSignup').disabled=true;$('signupMsg').textContent='جاري إنشاء الحساب...';try{const{data,error}=await db.auth.signUp({phone,password,options:{data:{full_name:name}}});if(error){$('signupMsg').textContent='تعذر إنشاء الحساب: '+error.message}else if(data.session){$('signupMsg').textContent='تم إنشاء الحساب وتسجيل الدخول.';setTimeout(()=>close('authModal'),700)}else{$('signupOtpPhone').value=phone;$('signupOtpBox').classList.remove('hidden');$('signupMsg').textContent='لو إعداد SMS مضبوط، هيوصلك كود تأكيد. اكتبه تحت.'}}catch(e){$('signupMsg').textContent='حصل خطأ في الاتصال. جرّب تاني.'}finally{$('doSignup').disabled=false}};
$('verifySignupOtp').onclick=async()=>{const phone=normalizePhone($('signupOtpPhone').value),token=$('signupOtp').value.trim();if(!phone||!token)return $('signupMsg').textContent='اكتب كود التأكيد.';$('verifySignupOtp').disabled=true;$('signupMsg').textContent='جاري تأكيد الرقم...';try{const{error}=await db.auth.verifyOtp({phone,token,type:'sms'});if(error){$('signupMsg').textContent='تعذر تأكيد الرقم: '+error.message}else{$('signupMsg').textContent='تم تأكيد الرقم وإنشاء الحساب.';setTimeout(()=>close('authModal'),700)}}catch(e){$('signupMsg').textContent='حصل خطأ. جرّب تاني.'}finally{$('verifySignupOtp').disabled=false}};
$('sendResetOtp').onclick=async()=>{const phone=normalizePhone($('resetPhone').value);if(!phone)return $('resetMsg').textContent='اكتب رقم الموبايل المسجل بالحساب.';$('sendResetOtp').disabled=true;$('resetMsg').textContent='جاري إرسال كود الاستعادة...';try{const{error}=await db.auth.signInWithOtp({phone,options:{shouldCreateUser:false}});if(error){$('resetMsg').textContent='تعذر إرسال الكود: '+error.message}else{$('resetOtpBox').classList.remove('hidden');$('resetMsg').textContent='لو إعداد SMS شغال والرقم مسجل، هيوصلك كود الاستعادة.'}}catch(e){$('resetMsg').textContent='حصل خطأ في الاتصال. جرّب تاني.'}finally{$('sendResetOtp').disabled=false}};
$('verifyResetOtp').onclick=async()=>{const phone=normalizePhone($('resetPhone').value),token=$('resetOtp').value.trim(),password=$('resetNewPassword').value;if(!phone||!token||password.length<6)return $('resetMsg').textContent='اكتب كود التأكيد وكلمة مرور جديدة (6 أحرف على الأقل).';$('verifyResetOtp').disabled=true;$('resetMsg').textContent='جاري التحقق وتغيير كلمة المرور...';try{const{error:verifyError}=await db.auth.verifyOtp({phone,token,type:'sms'});if(verifyError){$('resetMsg').textContent='الكود غير صحيح أو انتهت صلاحيته: '+verifyError.message;return}const{error:updateError}=await db.auth.updateUser({password});if(updateError){$('resetMsg').textContent='تم تأكيد الرقم لكن تعذر تغيير كلمة المرور: '+updateError.message;return}$('resetMsg').textContent='تم تغيير كلمة المرور بنجاح. تقدر تدخل الآن.';setTimeout(()=>authMode('login'),1000)}catch(e){$('resetMsg').textContent='حصل خطأ. جرّب تاني.'}finally{$('verifyResetOtp').disabled=false}};
db.auth.getSession().then(({data})=>{currentUser=data.session?.user||null;setAuthUI();if(currentUser){$('customerName').value=currentUser.user_metadata?.full_name||'';$('customerPhone').value=currentUser.phone||''}});db.auth.onAuthStateChange((_event,s)=>{currentUser=s?.user||null;setAuthUI();if(currentUser){$('customerName').value=currentUser.user_metadata?.full_name||$('customerName').value;$('customerPhone').value=currentUser.phone||$('customerPhone').value}});

async function load(){let all=[],from=0;while(from<TOTAL_PIXELS){const to=Math.min(from+999,TOTAL_PIXELS-1);const{data,error}=await db.from('pixels').select('*').order('pixel_number').range(from,to);if(error){board.innerHTML='<p>حصل خطأ في تحميل اللوحة.</p>';return}all=all.concat(data||[]);if(!data||data.length<1000)break;from+=1000}pixels=all;render();totals()}
function render(){board.innerHTML='';const byNumber=new Map(pixels.map(p=>[p.pixel_number,p]));let sold=0;for(let number=1;number<=TOTAL_PIXELS;number++){const p=byNumber.get(number)||{pixel_number:number,sold:false};const e=document.createElement('button');e.type='button';e.className='pixel '+(p.sold?'sold':'available')+(selected.has(p.pixel_number)?' selected':'');if(p.sold){sold++;if(p.ad_image_path)e.classList.add('has-ad')}else e.title='بيكسل #'+p.pixel_number;e.onclick=()=>{if(!p.sold){selected.has(p.pixel_number)?selected.delete(p.pixel_number):selected.add(p.pixel_number);render();totals()}};e.oncontextmenu=ev=>{ev.preventDefault();showDetails(p)};board.appendChild(e)}$('availableCount').textContent=(TOTAL_PIXELS-sold).toLocaleString('en-US')}
function totals(){$('selectedCount').textContent=selected.size;$('totalPrice').textContent=money(selected.size*PRICE);$('checkoutCount').textContent=selected.size;$('checkoutPrice').textContent=money(selected.size*PRICE)}
function open(id){$(id).classList.add('show')}function close(id){$(id).classList.remove('show')}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>close(x.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)close(m.id)});
$('reserveButton').onclick=()=>{if(!selected.size)return alert('اختار بيكسل واحد على الأقل.');if(!currentUser){authMode('login');open('authModal');$('loginMsg').textContent='سجل دخولك الأول عشان نحفظ مشترياتك في حسابك.';return}open('orderModal')};
document.querySelectorAll('[name=payment]').forEach(x=>x.onchange=()=>{const insta=document.querySelector('[name=payment]:checked').value==='instapay';$('instapayBox').classList.toggle('hidden',!insta);$('otherPayBox').classList.toggle('hidden',insta)});
async function upload(bucket,file){if(!file)return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=crypto.randomUUID()+'-'+safe;const{error}=await db.storage.from(bucket).upload(path,file,{upsert:false});if(error)throw error;return path}
async function submit(){const n=$('customerName').value.trim(),ph=normalizePhone($('customerPhone').value),an=$('adName').value.trim(),method=document.querySelector('[name=payment]:checked').value,pf=$('paymentProof').files[0],af=$('adImage').files[0];if(!currentUser)return $('orderMsg').textContent='سجل دخولك الأول.';if(!n||!ph||!an)return $('orderMsg').textContent='اكتب الاسم والموبايل واسم الإعلان.';if(method==='instapay'&&!pf)return $('orderMsg').textContent='ارفع إثبات الدفع.';if(method==='other'&&!$('otherPayment').value.trim())return $('orderMsg').textContent='اكتب طريقة الدفع.';const ids=[...selected];if(!ids.length)return $('orderMsg').textContent='اختار بيكسلات أولاً.';const fresh=await db.from('pixels').select('pixel_number,sold').in('pixel_number',ids);if(fresh.error)return $('orderMsg').textContent='تعذر التأكد من حالة البيكسلات.';if((fresh.data||[]).some(p=>p.sold)){await load();return $('orderMsg').textContent='بعض البيكسلات اتباعت بالفعل، اختار غيرها.'}
$('submitOrder').disabled=true;$('orderMsg').textContent='جاري إرسال الطلب...';try{const ap=await upload('ad-images',af),pp=await upload('payment-proofs',pf),num='PXL-'+Date.now().toString().slice(-8);const{error}=await db.from('pixel_orders').insert({order_number:num,customer_id:currentUser.id,customer_name:n,customer_phone:ph,ad_name:an,ad_text:$('adText').value.trim()||null,ad_link:$('adLink').value.trim()||null,ad_image_path:ap,payment_method:method,other_payment:method==='other'?$('otherPayment').value.trim():null,payment_proof_path:pp,selected_pixels:ids,pixel_count:ids.length,total_price:ids.length*PRICE,status:'pending'});if(error)throw error;$('orderMsg').textContent='تم إرسال الطلب بنجاح: '+num;selected.clear();totals();setTimeout(()=>{close('orderModal');$('orderMsg').textContent=''},1800)}catch(e){$('orderMsg').textContent='حصل خطأ: '+(e.message||e)}finally{$('submitOrder').disabled=false}}
$('submitOrder').onclick=submit;
$('supportButton').onclick=()=>open('supportModal');$('sendSupport').onclick=async()=>{const n=$('supportName').value.trim(),p=$('supportPhone').value.trim(),m=$('supportMessage').value.trim();if(!n||!p||!m)return $('supportMsg').textContent='املأ كل البيانات.';const{error}=await db.from('support_messages').insert({customer_name:n,customer_phone:p,message:m});$('supportMsg').textContent=error?'حصل خطأ: '+error.message:'تم إرسال رسالتك بنجاح.'};
function showDetails(p){if(!p.sold){$('pixelDetails').innerHTML='<h2>بيكسل #'+p.pixel_number+'</h2><p>البيكسل ده متاح للشراء بسعر <b>10 جنيه</b>.</p><button class="primary" onclick="close(\'detailModal\');selected.add('+p.pixel_number+');render();totals()">اختار البيكسل</button>'}else{$('pixelDetails').innerHTML='<h2>'+esc(p.ad_name||'إعلان')+'</h2><p><b>بيكسل #'+p.pixel_number+'</b></p>'+(p.ad_image_path?'<img class="detail-image" src="'+imageUrl(p.ad_image_path)+'" alt="">':'')+'<p>'+esc(p.ad_text||'')+'</p>'+(p.ad_link?'<a class="ad-link" href="'+escAttr(p.ad_link)+'" target="_blank" rel="noopener">زيارة الإعلان</a>':'')+'<p class="sold-label">هذا المكان مباع</p>'}open('detailModal')}
function imageUrl(path){return db.storage.from('ad-images').getPublicUrl(path).data.publicUrl}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escAttr(s){return esc(s)}
$('zoomIn').onclick=()=>setZoom(scale+.25);$('zoomOut').onclick=()=>setZoom(Math.max(.5,scale-.25));$('zoomReset').onclick=()=>setZoom(1);function setZoom(v){scale=v;board.style.transform='scale('+scale+')';board.style.transformOrigin='top center';board.parentElement.style.minHeight=(1800*scale+40)+'px'}
const sheet=$('checkoutSheet'),handle=$('checkoutHandle');let dragStartY=0,dragging=false,sheetStart=0;
function setSheetCollapsed(collapsed){sheet.classList.toggle('collapsed',collapsed)}
handle.addEventListener('pointerdown',e=>{dragging=true;dragStartY=e.clientY;sheetStart=sheet.classList.contains('collapsed')?1:0;handle.setPointerCapture(e.pointerId);sheet.style.transition='none'});
handle.addEventListener('pointermove',e=>{if(!dragging)return;const dy=e.clientY-dragStartY;if(Math.abs(dy)<3)return;const height=sheet.offsetHeight;let progress=sheetStart+(dy/Math.max(height,1));progress=Math.max(0,Math.min(1,progress));sheet.style.transform='translate(-50%,calc('+progress+' * (100% - 70px)))'});
handle.addEventListener('pointerup',e=>{if(!dragging)return;dragging=false;sheet.releasePointerCapture(e.pointerId);sheet.style.transition='transform .22s ease';const dy=e.clientY-dragStartY;setSheetCollapsed(sheetStart?dy> -40:dy>40)});
handle.addEventListener('pointercancel',()=>{dragging=false;sheet.style.transition='transform .22s ease';setSheetCollapsed(sheetStart===1)});
load();setInterval(load,15000);