const db=supabase.createClient('https://uklivylyenatdqbgmcxy.supabase.co','sb_publishable_ntlKWYQvMXlCs_obIEVIIA_-CfxOFTJ');const PRICE=10,TOTAL_PIXELS=22500,$=id=>document.getElementById(id),board=$('pixelBoard'),selected=new Set();let pixels=[],pixelByNumber=new Map(),scale=1,currentUser=null;
const money=n=>n.toLocaleString('en-US')+' جنيه';
function normalizePhone(v){let x=String(v||'').replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[^0-9+]/g,'');if(x.startsWith('00'))x='+'+x.slice(2);if(x.startsWith('01'))x='+20'+x.slice(1);if(x.startsWith('20')&&!x.startsWith('+'))x='+'+x;return x}
function setAuthUI(){const logged=!!currentUser;$('accountStatus').textContent=logged?'حسابك مسجل الدخول':'زائر';$('loginButton').classList.toggle('hidden',logged);$('accountButton').classList.toggle('hidden',!logged);$('logoutButton').classList.toggle('hidden',!logged)}
function authMode(mode){$('loginForm').classList.toggle('hidden',mode!=='login');$('signupForm').classList.toggle('hidden',mode!=='signup');$('resetForm').classList.toggle('hidden',mode!=='reset');$('loginTab').classList.toggle('active',mode==='login');$('signupTab').classList.toggle('active',mode==='signup')}
$('loginButton').onclick=()=>{authMode('login');open('authModal')};$('accountButton').onclick=async()=>{if(!currentUser){authMode('login');open('authModal');return}open('accountModal');await loadAccountStats()};$('leaderboardButton').onclick=async()=>{open('leaderboardModal');await loadLeaderboard()};$('accountLogout').onclick=async()=>{await db.auth.signOut();currentUser=null;selected.clear();setAuthUI();totals();close('accountModal')};$('deleteAccount').onclick=async()=>{if(!currentUser)return;if(!confirm('هل أنت متأكد من حذف حسابك نهائيًا؟ لا يمكن التراجع عن هذا الإجراء.'))return;$('deleteAccount').disabled=true;$('accountMsg').textContent='جاري حذف الحساب...';try{const{data,error}=await db.functions.invoke('delete-account');if(error)throw error;if(!data?.success)throw new Error(data?.error||'تعذر حذف الحساب');await db.auth.signOut();currentUser=null;setAuthUI();close('accountModal');alert('تم حذف الحساب.')}catch(e){$('accountMsg').textContent='تعذر حذف الحساب: '+(e.message||e)}finally{$('deleteAccount').disabled=false}};$('loginTab').onclick=()=>authMode('login');$('signupTab').onclick=()=>authMode('signup');$('forgotPassword').onclick=()=>{authMode('reset');$('resetMsg').textContent='';$('resetPasswordBox').classList.add('hidden')};$('backToLogin').onclick=()=>authMode('login');$('logoutButton').onclick=async()=>{await db.auth.signOut();selected.clear();totals()};
$('doLogin').onclick=async()=>{const email=$('loginEmail').value.trim().toLowerCase(),password=$('loginPassword').value;if(!email||!password)return $('loginMsg').textContent='اكتب الإيميل وكلمة المرور.';$('doLogin').disabled=true;$('loginMsg').textContent='جاري تسجيل الدخول...';try{const{error}=await db.auth.signInWithPassword({email,password});if(error){const m=error.message||'';$('loginMsg').textContent=/invalid login credentials|invalid_credentials/i.test(m)?'الإيميل أو كلمة المرور غير صحيحة.':/email_not_confirmed/i.test(m)?'أكد الإيميل من الرسالة اللي وصلتك الأول.':'تعذر تسجيل الدخول: '+m}else{$('loginMsg').textContent='تم تسجيل الدخول.';setTimeout(()=>close('authModal'),500)}}catch(e){$('loginMsg').textContent='حصل خطأ في الاتصال. جرّب تاني.'}finally{$('doLogin').disabled=false}};
$('doSignup').onclick=async()=>{const username=$('signupUsername').value.trim(),email=$('signupEmail').value.trim().toLowerCase(),password=$('signupPassword').value;if(!username||!email||password.length<6)return $('signupMsg').textContent='اكتب اسم المستخدم والإيميل وكلمة مرور 6 أحرف أو أكثر.';if(!/^[^\s@]+@[^\s@]+\.[A-Za-z]{2,}$/.test(email))return $('signupMsg').textContent='الإيميل مش مكتوب بشكل صحيح. اكتب إيميل كامل زي name@gmail.com، مش اسم المستخدم بس.';if(!/^[a-zA-Z0-9_.-]{3,24}$/.test(username))return $('signupMsg').textContent='اسم المستخدم لازم يكون من 3 إلى 24 حرفًا، باستخدام حروف إنجليزية أو أرقام أو . _ -';$('doSignup').disabled=true;$('signupMsg').textContent='جاري إنشاء الحساب...';try{const{data,error}=await db.auth.signUp({email,password,options:{data:{username,full_name:username},emailRedirectTo:'https://pixelforsale-bwu8.vercel.app/?auth=login'}});if(error){$('signupMsg').textContent='تعذر إنشاء الحساب: '+error.message}else if(data.session){currentUser=data.user;setAuthUI();$('signupMsg').textContent='تم إنشاء الحساب وتسجيل الدخول.';setTimeout(()=>close('authModal'),700)}else{$('signupMsg').textContent='طلب إنشاء الحساب اتبعت. افتح الإيميل واضغط رابط التأكيد، وبعدها سجّل دخولك.'}}catch(e){$('signupMsg').textContent='حصل خطأ في الاتصال. جرّب تاني.'}finally{$('doSignup').disabled=false}};
$('sendResetEmail').onclick=async()=>{const email=$('resetEmail').value.trim().toLowerCase();if(!email)return $('resetMsg').textContent='اكتب الإيميل المسجل بالحساب.';$('sendResetEmail').disabled=true;$('resetMsg').textContent='جاري إرسال رابط الاستعادة...';try{const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:'https://pixelforsale-bwu8.vercel.app/?reset=1'});if(error){$('resetMsg').textContent='تعذر إرسال رابط الاستعادة: '+error.message}else{$('resetMsg').textContent='لو الإيميل مسجل، هتوصلك رسالة فيها رابط تعيين كلمة مرور جديدة. راجع Spam كمان.'}}catch(e){$('resetMsg').textContent='حصل خطأ في الاتصال. جرّب تاني.'}finally{$('sendResetEmail').disabled=false}};
$('saveNewPassword').onclick=async()=>{const password=$('resetNewPassword').value;if(password.length<6)return $('resetMsg').textContent='اكتب كلمة مرور جديدة من 6 أحرف على الأقل.';$('saveNewPassword').disabled=true;$('resetMsg').textContent='جاري حفظ كلمة المرور...';try{const{error}=await db.auth.updateUser({password});if(error){$('resetMsg').textContent='تعذر تغيير كلمة المرور: '+error.message}else{$('resetMsg').textContent='تم تغيير كلمة المرور. تقدر تسجل الدخول دلوقتي.';$('resetNewPassword').value='';setTimeout(()=>authMode('login'),1200)}}catch(e){$('resetMsg').textContent='حصل خطأ. افتح رابط الاستعادة من الإيميل مرة تانية.'}finally{$('saveNewPassword').disabled=false}};
(async()=>{const params=new URLSearchParams(location.search);if(params.get('auth')==='login'){await db.auth.signOut();currentUser=null;setAuthUI();authMode('login');open('authModal');history.replaceState({},'',location.pathname);return}const{data}=await db.auth.getSession();currentUser=data.session?.user||null;setAuthUI();if(currentUser){$('customerName').value=currentUser.user_metadata?.full_name||currentUser.user_metadata?.username||'';$('customerPhone').value=currentUser.phone||''}if(params.get('reset')==='1'){authMode('reset');open('authModal')}})();
db.auth.onAuthStateChange((event,s)=>{currentUser=s?.user||null;setAuthUI();if(currentUser){$('customerName').value=currentUser.user_metadata?.full_name||currentUser.user_metadata?.username||$('customerName').value;$('customerPhone').value=currentUser.phone||$('customerPhone').value}if(event==='PASSWORD_RECOVERY'){authMode('reset');$('resetPasswordBox').classList.remove('hidden');$('resetMsg').textContent='تم التحقق من رابط الاستعادة. اكتب كلمة المرور الجديدة.';open('authModal')}});


async function load(){board.setAttribute('aria-busy','true');const ranges=[];for(let from=0;from<TOTAL_PIXELS;from+=1000)ranges.push([from,Math.min(from+999,TOTAL_PIXELS-1)]);const pages=await Promise.all(ranges.map(([from,to])=>db.from('pixels').select('pixel_number,sold,ad_image_path,ad_name,ad_text,ad_link').order('pixel_number').range(from,to)));const bad=pages.find(r=>r.error);if(bad){board.innerHTML='<p>حصل خطأ في تحميل اللوحة. حدّث الصفحة وجرب تاني.</p>';board.removeAttribute('aria-busy');return}pixels=pages.flatMap(r=>r.data||[]);render();totals();board.removeAttribute('aria-busy')}
function render(){const fragment=document.createDocumentFragment();pixelByNumber=new Map(pixels.map(p=>[Number(p.pixel_number),p]));let sold=0;for(let number=1;number<=TOTAL_PIXELS;number++){const p=pixelByNumber.get(number)||{pixel_number:number,sold:false};const e=document.createElement('button');e.type='button';e.dataset.number=String(number);e.setAttribute('aria-label','بيكسل '+number);e.className='pixel '+(p.sold?'sold':'available')+(selected.has(number)?' selected':'');if(p.sold){sold++;if(p.ad_image_path)e.classList.add('has-ad')}else e.title='بيكسل #'+number;fragment.appendChild(e)}board.replaceChildren(fragment);$('availableCount').textContent=(TOTAL_PIXELS-sold).toLocaleString('en-US')}
board.addEventListener('click',e=>{const el=e.target.closest('.pixel');if(!el||!board.contains(el))return;const number=Number(el.dataset.number),p=pixelByNumber.get(number);if(p?.sold)return;if(selected.has(number)){selected.delete(number);el.classList.remove('selected')}else{selected.add(number);el.classList.add('selected')}totals()});board.addEventListener('contextmenu',e=>{const el=e.target.closest('.pixel');if(!el||!board.contains(el))return;e.preventDefault();const number=Number(el.dataset.number);showDetails(pixelByNumber.get(number)||{pixel_number:number,sold:false})});
function totals(){$('selectedCount').textContent=selected.size;$('totalPrice').textContent=money(selected.size*PRICE);$('checkoutCount').textContent=selected.size;$('checkoutPrice').textContent=money(selected.size*PRICE)}
async function loadAccountStats(){if(!currentUser)return;$('accountIdentity').textContent=currentUser.user_metadata?.username||currentUser.email||'حسابك';$('myPixelCount').textContent='...';$('mySpent').textContent='...';$('accountMsg').textContent='';const{data,error}=await db.rpc('my_pixel_stats');if(error){$('accountMsg').textContent='تعذر تحميل إحصائيات الحساب: '+error.message;return}const v=Array.isArray(data)?data[0]:data;$('myPixelCount').textContent=Number(v?.pixel_count||0).toLocaleString('en-US');$('mySpent').textContent=money(Number(v?.total_spent||0));$('accountMsg').textContent='الإحصائيات تشمل الطلبات التي تم اعتمادها فقط.'}
async function loadLeaderboard(){const el=$('leaderboardList');el.textContent='جاري تحميل الترتيب...';const{data,error}=await db.rpc('pixel_leaderboard');if(error){el.textContent='تعذر تحميل الترتيب: '+error.message;return}if(!data?.length){el.textContent='لسه مفيش مشتريات معتمدة.';return}el.innerHTML=data.map((v,i)=>'<div class="leaderboard-row"><span class="leaderboard-rank">#'+(i+1)+'</span><div><div class="leaderboard-name">'+esc(v.username||'مستخدم')+'</div><div class="leaderboard-meta">'+Number(v.pixel_count||0).toLocaleString('en-US')+' بيكسل</div></div><div class="leaderboard-total">'+money(Number(v.total_spent||0))+'</div></div>').join('')}
function open(id){$(id).classList.add('show')}function close(id){$(id).classList.remove('show')}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>close(x.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)close(m.id)});
$('reserveButton').onclick=()=>{if(!selected.size)return alert('اختار بيكسل واحد على الأقل.');if(!currentUser){authMode('login');open('authModal');$('loginMsg').textContent='سجل دخولك الأول عشان نحفظ مشترياتك في حسابك.';return}open('orderModal')};
document.querySelectorAll('[name=payment]').forEach(x=>x.onchange=()=>{const insta=document.querySelector('[name=payment]:checked').value==='instapay';$('instapayBox').classList.toggle('hidden',!insta);$('otherPayBox').classList.toggle('hidden',insta)});
async function upload(bucket,file){if(!file)return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=crypto.randomUUID()+'-'+safe;const{error}=await db.storage.from(bucket).upload(path,file,{upsert:false});if(error)throw error;return path}
async function submit(){const n=$('customerName').value.trim(),ph=normalizePhone($('customerPhone').value),an=$('adName').value.trim(),method=document.querySelector('[name=payment]:checked').value,pf=$('paymentProof').files[0],af=$('adImage').files[0];if(!currentUser)return $('orderMsg').textContent='سجل دخولك الأول.';if(!n||!ph||!an)return $('orderMsg').textContent='اكتب الاسم والموبايل واسم الإعلان.';if(method==='instapay'&&!pf)return $('orderMsg').textContent='ارفع إثبات الدفع.';if(method==='other'&&!$('otherPayment').value.trim())return $('orderMsg').textContent='اكتب طريقة الدفع.';const ids=[...selected];if(!ids.length)return $('orderMsg').textContent='اختار بيكسلات أولاً.';const fresh=await db.from('pixels').select('pixel_number,sold').in('pixel_number',ids);if(fresh.error)return $('orderMsg').textContent='تعذر التأكد من حالة البيكسلات.';if((fresh.data||[]).some(p=>p.sold)){await load();return $('orderMsg').textContent='بعض البيكسلات اتباعت بالفعل، اختار غيرها.'}
$('submitOrder').disabled=true;$('orderMsg').textContent='جاري إرسال الطلب...';try{const ap=af?await upload('ad-images',af):null,pp=pf?await upload('payment-proofs',pf):null,num='PXL-'+Date.now().toString().slice(-8);const{error}=await db.from('pixel_orders').insert({order_number:num,customer_id:currentUser.id,customer_name:n,customer_phone:ph,ad_name:an,ad_text:$('adText').value.trim()||null,ad_link:$('adLink').value.trim()||null,ad_image_path:ap,payment_method:method,other_payment:method==='other'?$('otherPayment').value.trim():null,payment_proof_path:pp,selected_pixels:ids,pixel_count:ids.length,total_price:ids.length*PRICE,status:'pending'});if(error)throw error;$('orderMsg').textContent='تم إرسال الطلب بنجاح: '+num;selected.clear();totals();setTimeout(()=>{close('orderModal');$('orderMsg').textContent=''},1800)}catch(e){$('orderMsg').textContent='حصل خطأ: '+(e.message||e)}finally{$('submitOrder').disabled=false}}
$('submitOrder').onclick=submit;
$('supportButton').onclick=()=>open('supportModal');$('sendSupport').onclick=async()=>{const n=$('supportName').value.trim(),p=$('supportPhone').value.trim(),m=$('supportMessage').value.trim();if(!n||!p||!m)return $('supportMsg').textContent='املأ كل البيانات.';const{error}=await db.from('support_messages').insert({customer_name:n,customer_phone:p,message:m});$('supportMsg').textContent=error?'حصل خطأ: '+error.message:'تم إرسال رسالتك بنجاح.'};
function showDetails(p){if(!p.sold){$('pixelDetails').innerHTML='<h2>بيكسل #'+p.pixel_number+'</h2><p>البيكسل ده متاح للشراء بسعر <b>10 جنيه</b>.</p><button class="primary" onclick="close(\'detailModal\');selected.add('+p.pixel_number+');render();totals()">اختار البيكسل</button>'}else{$('pixelDetails').innerHTML='<h2>'+esc(p.ad_name||'إعلان')+'</h2><p><b>بيكسل #'+p.pixel_number+'</b></p>'+(p.ad_image_path?'<img class="detail-image" src="'+imageUrl(p.ad_image_path)+'" alt="">':'')+'<p>'+esc(p.ad_text||'')+'</p>'+(p.ad_link?'<a class="ad-link" href="'+escAttr(p.ad_link)+'" target="_blank" rel="noopener">زيارة الإعلان</a>':'')+'<p class="sold-label">هذا المكان مباع</p>'}open('detailModal')}
function imageUrl(path){return db.storage.from('ad-images').getPublicUrl(path).data.publicUrl}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escAttr(s){return esc(s)}
$('zoomIn').onclick=()=>setZoom(scale+.25);$('zoomOut').onclick=()=>setZoom(Math.max(.5,scale-.25));$('zoomReset').onclick=()=>setZoom(1);function setZoom(v){scale=v;board.style.transform='scale('+scale+')';board.style.transformOrigin='top center';board.parentElement.style.minHeight=(1800*scale+40)+'px'}
const sheet=$('checkoutSheet'),handle=$('checkoutHandle');let dragStartY=0,dragging=false,sheetStart=0;
function setSheetCollapsed(collapsed){sheet.classList.toggle('collapsed',collapsed)}
handle.addEventListener('pointerdown',e=>{dragging=true;dragStartY=e.clientY;sheetStart=sheet.classList.contains('collapsed')?1:0;handle.setPointerCapture(e.pointerId);sheet.style.transition='none'});
handle.addEventListener('pointermove',e=>{if(!dragging)return;const dy=e.clientY-dragStartY;if(Math.abs(dy)<3)return;const height=sheet.offsetHeight;let progress=sheetStart+(dy/Math.max(height,1));progress=Math.max(0,Math.min(1,progress));sheet.style.transform='translate(-50%,calc('+progress+' * (100% - 70px)))'});
handle.addEventListener('pointerup',e=>{if(!dragging)return;dragging=false;sheet.releasePointerCapture(e.pointerId);sheet.style.transition='transform .22s ease';const dy=e.clientY-dragStartY;setSheetCollapsed(sheetStart?dy> -40:dy>40)});
handle.addEventListener('pointercancel',()=>{dragging=false;sheet.style.transition='transform .22s ease';setSheetCollapsed(sheetStart===1)});
load();